### ISSUE TITLE
Snyk protect

### ISSUE THREAD

**Issue by jwheare** [flathub/com.irccloud.desktop#3]
I assume the [disable-snyk.patch](https://github.com/flathub/com.irccloud.desktop/blob/b7510246d98868fcfb2e47c602f6d52dcf306a9a/disable-snyk.patch) is in place because if snyk patches any dependencies, it could generate a hash mismatch in generated sources?

This isn't ideal, since it means any critical security patches would be missing from flatpak builds. Is there a way to update the sources hashes after snyk-protect has been run?

**Comment by barthalion** [comment]
(Oops, sorry, missed the notification somehow.)

Flathub builds are done offline, so I had to patch it out. Not sure how Snyk works but ideally it's something that is already reflected by the lock file in IRCCloud repository, and then the script used for creating generated sources doesn't need to be bothered about it.
